[CBRD-23812] [Regression] The results of two queries that scan different indexes in the same transaction are different.
CUBRID/cubrid pull request #2542
Opened 2021-01-08 04:10 UTC by byungwook-kim

http://jira.cubrid.org/browse/CBRD-23812
also related to http://jira.cubrid.org/browse/CBRD-23731

Environment:

Create a table by increasing columns from 2 to 30.
Insert/update/select sequentially with 10 threads targeting each table.
10,000 times per thread.
Fail case:
When comparing each column value by executing the same select query that scans different indexes in the same transaction, in the select result comparison step, the result of the first query is failing with 0 tuple.

I changed the default type to VARCHAR for constant string.
And I also modified comparing routine mr_cmpval_string and mr_cmpval_char.
In the modified comparing routine, varchar-type data comparing always no ignore trailing spaces and char-type data comparing always ignore trailing spaces.

NVL and CONCAT function is fixed for return to origin column's type

2021-01-11 04:26 UTC, hgryoo commented on src/parser/csql_grammar.y
> +	  }
indent

2021-01-11 04:30 UTC, hgryoo requested changes
For host variables, it is necessary to consider the type handling of constant values modified in this PR.

2021-01-11 05:18 UTC, shparkcubrid commented on src/parser/csql_grammar.y
> +
indent

2021-01-11 05:19 UTC, shparkcubrid commented on src/parser/csql_grammar.y
> +
indent

2021-01-11 23:30 UTC, byungwook-kim commented on src/parser/csql_grammar.y
> +	  }
I fixed it.

2021-01-11 23:31 UTC, byungwook-kim commented on src/parser/csql_grammar.y
> +
I fixed it.

2021-01-11 23:31 UTC, byungwook-kim commented on src/parser/csql_grammar.y
> +
I fixed it.

2021-01-13 00:38 UTC, hgryoo commented on src/compat/db_vdb.c
>      }
indent

2021-01-13 00:39 UTC, hgryoo commented on src/object/object_primitive.c
> +            }
indent

2021-01-13 00:39 UTC, hgryoo commented on src/object/object_primitive.c
> +        }
indent

2021-01-13 01:41 UTC, shparkcubrid approved these changes

2021-01-13 01:49 UTC, hgryoo approved these changes

2021-01-13 01:54 UTC, merged