[CBRD-23926] Use statistics of pages when checking recompilation threshold.
CUBRID/cubrid pull request #2736
Opened 2021-04-27 06:21 UTC by shparkcubrid

http://jira.cubrid.org/browse/CBRD-23926

After the use_stat_estimation parameter is added, the default is not to automatically update the page of the table.
If the use_stat_estimation parameter is not set, modify to use the statistics pages instead of the current pages when checking recompilation threshold.

2021-04-27 08:47 UTC, ctshim commented on src/query/xasl_cache.c
> +      if (!use_stat_estimation)
remove the use_stat_estimation variable,
How about changing it like below?
```suggestion
      if (!prm_get_bool_value (PRM_ID_USE_STAT_ESTIMATION))
```

2021-04-27 08:49 UTC, ctshim commented on src/query/xasl_cache.c
> +  bool use_stat_estimation = prm_get_bool_value (PRM_ID_USE_STAT_ESTIMATION);
The use_stat_estimation variable can be removed by modifying the if() statement below.
```suggestion  
```

2021-04-27 08:52 UTC, ctshim approved these changes

2021-04-27 08:56 UTC, hgryoo approved these changes

2021-04-27 23:08 UTC, youngjinj approved these changes

2021-04-28 01:05 UTC, byungwook-kim approved these changes

2021-04-28 02:41 UTC, youngjinj requested changes

2021-04-28 05:28 UTC, youngjinj commented on src/query/xasl_cache.c
> +      if (!prm_get_bool_value (PRM_ID_USE_STAT_ESTIMATION))
I was misunderstanding. I listened to the explanation and understood.

2021-04-28 05:28 UTC, youngjinj approved these changes

2021-04-28 05:30 UTC, merged