[LETS-126] - Include unit tests in the appveyor build
CUBRID/cubrid pull request #2869
Opened 2021-06-29 15:49 UTC by danilailie

http://jira.cubrid.org/browse/LETS-126

* Fixed unit tests compile errors for windows.

2021-06-30 07:50 UTC, ribram requested changes
The issue (and PR title) mentions including building unit tests in the appveyor build. Update .appveyor.yml.

2021-06-30 07:50 UTC, ribram commented on unit_tests/log/dummy_page_server.cpp
> +#include "log_replication.hpp"
Add license header.

2021-06-30 07:50 UTC, ribram commented on unit_tests/log/CMakeLists.txt
>  if(UNIX)
Why are these unit tests limited to linux?

2021-06-30 07:50 UTC, ribram commented on unit_tests/packing/CMakeLists.txt
>  else()
Is this change required? I think test_packing does not need fake_thread_utils.

2021-06-30 07:50 UTC, ribram commented on unit_tests/log/CMakeLists.txt
> +target_link_libraries(test_log_lsa_utils fake_thread_utils)
Does test_log_lsa_utils depend on fake_thread_util? It doesn't like it does. If it is does not, better to remove the line completely.

2021-07-01 09:26 UTC, ribram commented on unit_tests/log/ut_database.hpp
> +    std::discrete_distribution<int32_t> m_add_or_update_page_dist;
Why this change? Please explain.

2021-07-01 09:27 UTC, ribram commented
@danilailie the appveyor build is still missing -DUNIT_TESTS option that triggers unit test compilation.

2021-07-01 09:43 UTC, danilailie commented on unit_tests/log/ut_database.hpp
> +    std::discrete_distribution<int32_t> m_add_or_update_page_dist;
On vs compiler it complains that the template instantiation with an 8 bit type is illegal.

2021-07-01 12:13 UTC, ribram commented on unit_tests/log/ut_database.hpp
> +    std::discrete_distribution<int32_t> m_add_or_update_page_dist;
Right, the standard documentation for [discrete_distribution](https://en.cppreference.com/w/cpp/numeric/random/discrete_distribution) mentions:

<html>
<body>
<!--StartFragment--><h3 style="color: rgb(0, 0, 0); background: none rgb(255, 255, 255); font-weight: bold; margin: 0px 0px 0.3em; overflow: hidden; padding: 1.1em 0px 0.2em 0.75em; border-bottom: none; width: auto; font-size: 16.896px; font-family: DejaVuSans, &quot;DejaVu Sans&quot;, arial, sans-serif; font-style: normal; font-variant-ligatures: no-common-ligatures; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="mw-headline" id="Template_parameters">Template parameters</span></h3>

IntType | - | The result type generated by the generator. The effect is undefined if this is not one of short, int, long, long long, unsigned short, unsigned int, unsigned long, or unsigned long long.
-- | -- | --


<!--EndFragment-->
</body>
</html>

Shouldn't m_add_or_update_page_dist & m_add_or_update_page_dist usages be updated too, as consequence of this change?

2021-07-01 12:14 UTC, ribram commented
Please check appveyor error:
```
CMake Error: Could not create named generator Visual Studio 16 2019 Win64
CMake Error: CMAKE_GENERATOR was set but the specified generator doesn't exist. Using CMake default.
Generators
* Visual Studio 16 2019        = Generates Visual Studio 2019 project files.
                                 Use -A option to specify architecture.
  Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
                                 Optional [arch] can be "Win64" or "ARM".
```

2021-07-01 18:06 UTC, danilailie commented on unit_tests/log/ut_database.hpp
> +    std::discrete_distribution<int32_t> m_add_or_update_page_dist;
It's done

2021-07-02 09:46 UTC, ribram approved these changes

2021-07-02 10:48 UTC, merged