[LETS-237] There is no error message displayed when server type is misspelt
CUBRID/cubrid pull request #3082
Opened 2021-10-08 13:05 UTC by adrianbrab

jira.cubrid.org/browse/LETS-237

Printed the misspellt server type in terminal before closing the server.
Changed `ER_INVALID_SERVER_TYPE_ARGUMENT` error message to include the misspellt server type.

2021-10-11 06:37 UTC, ribram approved these changes

2021-10-11 09:41 UTC, cristiarg commented on src/executables/server.c
> +              er_set (ER_ERROR_SEVERITY, ARG_FILE_LINE, ER_INVALID_SERVER_TYPE_ARGUMENT, 1, optarg);	// error that the type is not valid
alignment, line exceeds 120 chars

2021-10-11 09:41 UTC, cristiarg commented on src/executables/server.c
> +        fflush (stderr);
This might not be the best approach.
The error should be printed in the scope where it appeared.
If there is more than one error that should be printed, only the last one will be printed.
Or if the function `argument_handler` is modified with the addition of another argument.

2021-10-11 09:41 UTC, cristiarg commented on src/executables/server.c
>            // *INDENT-OFF*
I suppose it is first indent `OFF` then `ON`?

2021-10-11 10:29 UTC, adrianbrab commented on src/executables/server.c
>            // *INDENT-OFF*
Fixed now.

2021-10-11 10:31 UTC, adrianbrab commented on src/executables/server.c
> +              er_set (ER_ERROR_SEVERITY, ARG_FILE_LINE, ER_INVALID_SERVER_TYPE_ARGUMENT, 1, optarg);	// error that the type is not valid
moved the comment before er_set

2021-10-11 10:58 UTC, adrianbrab commented on src/executables/server.c
> +        fflush (stderr);
Changed now to print inside argument_handler, but the function will always show just one error msg, the first one encountered.

2021-10-11 11:05 UTC, ribram commented on src/executables/server.c
> +        fflush (stderr);
The purpose is to print to console an error, not all. If there are more than one errors, they will be logged in the error log file. The approach of printing the error is taken from `net_server_start ()` function.

 My suggestion is a different one: add the error printing as scope_exit to `server.c:main()` function, and remove it from `net_server_start()` too. Printing the error to console in the end will also cover adding new function calls.
 
 @cristiarg @adrianbrab what do you think?

2021-10-11 11:46 UTC, adrianbrab commented on src/executables/server.c
> +        fflush (stderr);
I think this is the best approach to catch all errors, and also write future proof code.

2021-10-11 12:13 UTC, cristiarg approved these changes

2021-10-11 14:00 UTC, ribram requested changes

2021-10-11 14:00 UTC, ribram commented on src/executables/server.c
> +    });
- Error should be printed only if there was an error, reflected by ret_val's value.
- No point on capturing `thread_p`, but a reference to `ret_val` has to be captured.
```suggestion
    scope_exit <std::function<void (void)>> print_err_on_exit ([&ret_val] ()
    {
      if (ret_val != 0)
        {
          PRINT_AND_LOG_ERR_MSG ("%s\n", er_msg ());
          fflush (stderr);
        }
    });
```

2021-10-12 06:49 UTC, ribram approved these changes

2021-10-12 06:49 UTC, ribram commented on src/executables/server.c
> +#include "scope_exit.hpp"
No longer needed
```suggestion
```

2021-10-12 06:59 UTC, cristiarg approved these changes

2021-10-12 06:59 UTC, cristiarg commented on src/executables/server.c
> +	return 1;
Is there a reason to return 1/0?
```suggestion
	return ER_FAILED;
```
and `NO_ERROR` at the end

2021-10-12 08:42 UTC, ribram commented on src/executables/server.c
> +	return 1;
The main function returns an exit code, not the internal database error code. Other main functions return `EXIT_SUCCESS` or `EXIT_FAILURE`. They may be used here too to replace 1/0.

2021-10-12 14:06 UTC, merged