[CBRD-24883] combine with oracle_style_number_return parameter
CUBRID/cubrid pull request #4484
Opened 2023-07-11 23:44 UTC by beyondykk9

http://jira.cubrid.org/browse/CBRD-24883

It needs to merge two system parameters oracle_style_number_return and oracle_style_divide into one oracle_style_number_return.

There is no need to maintain two oracle-style number-related parameters. That is, the two parameters oracle_style_divide and oracle_style_number_return are unlikely to be used separately, so it is better to combine them into one.

2023-07-12 05:05 UTC, ctshim approved these changes

2023-07-12 05:17 UTC, hgryoo approved these changes

2023-07-12 05:43 UTC, hyunikn approved these changes

2023-07-12 07:07 UTC, hgryoo commented
We need to discuss renaming "oracle_style_number_return" to "oracle_compat_number_behavior" (just an example) due to the parameter's changing effects when combined with other parameters.

2023-07-12 07:10 UTC, hgryoo requested changes
Also, please update the JIRA about Specification changes and A/C

2023-07-13 04:07 UTC, beyondykk9 commented
> We need to discuss renaming "oracle_style_number_return" to "oracle_compat_number_behavior" (just an example) due to the parameter's changing effects when combined with other parameters.

I applied the parameter as your opinion.

2023-07-13 04:31 UTC, hgryoo approved these changes

2023-07-13 04:35 UTC, merged